---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cmd-script
data:
  cmd.js: |
    const axios = require('axios');
    const https = require('https');
    const qs = require('qs');

    const axios_instance = axios.create({
      httpsAgent: new https.Agent({  
        rejectUnauthorized: false
      })
    });
    
    console.log('setup keycloak');
    const keycloak_host = process.env.KEYCLOAK_SVC;
    const keycloak_port = process.env.KEYCLOAK_PORT;
    const admin_usr = process.env.KEYCLOAK_ADMIN_USR;
    const admin_pwd = process.env.KEYCLOAK_ADMIN_PWD;

    realm_data = {
      "realm":"example",
      "notBefore":0,
      "enabled":true,
      "sslRequired":"all",
      "bruteForceProtected":true,
      "failureFactor":10,
      "eventsEnabled":false
    };

    url_base = 'https://'+keycloak_host;
    data = {
        client_id: 'admin-cli',
        username: admin_usr,
        password: admin_pwd,
        grant_type: 'password'
    };
    tokencall_config = {
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
      },
      auth: {
        username: admin_usr,
        password: admin_pwd
      },
      responseType: 'json' // default
    };

    const setupKeycloak = async () => {
        console.log('base_url:',url_base);
        try {
            const resp = await axios_instance.post(url_base+'/auth/realms/master/protocol/openid-connect/token',qs.stringify(data),tokencall_config);
            data = resp.data;
            access_token = data.access_token;
            refresh_token = data.refresh_token;
            console.log('tokens: '+access_token+"    "+refresh_token);

            // Create realm
            realmcreate_config = {
              headers: {
                'Content-Type': 'application/json',
                'Authorization': 'Bearer '+access_token
              },
              responseType: 'json'
            };
            const realm_resp = await axios_instance.post(url_base+'/auth/admin/realms',realm_data,realmcreate_config);     
            rc_data = realm_resp.data;
            console.log('Realm Data:',realm_resp.status);
        } catch(error) {
            console.error("**** ERROR:", error);
        };
    };

    setupKeycloak();
